name: flutterproject2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  bloc: ^8.1.4
  equatable: ^2.0.5
  file_picker: ^8.1.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  image_picker: ^1.1.2
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/donmac.jpg
    - assets/donmacgif.gif
    - assets/donmacisreal.png
    - assets/donmacbg.jpg
    - assets/Productlist/blackforest.jpg
    - assets/Productlist/dondarko.jpg 
    - assets/Productlist/donmacnew.jpg
    - assets/Productlist/donyaberry.jpg
    - assets/Productlist/icedcaramel.jpg
    - assets/Productlist/macha.jpg
    - assets/Productlist/matchaberry.jpg
    - assets/yawa.png
    - assets/branchopol.png
    - assets/branchdasmarinas.png
    - assets/branchbuhisan.png
    - assets/branchtabunok.png
    - assets/branchbooth.png
    - assets/branchlingayen.png
