name: fmobile
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  http: ^1.2.2
  flutter_secure_storage: ^9.0.0
  intl: ^0.20.1
  timezone: ^0.10.0
  printing: ^5.13.4
  pdf: ^3.11.1
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  
  assets:

    - assets/donmac.jpg
    - assets/donmacgif.gif
    - assets/donmacisreal.png
    - assets/donmacbg.jpg
    - assets/Productlist/blackforest.jpg
    - assets/Productlist/dondarko.jpg 
    - assets/Productlist/donmacnew.jpg
    - assets/Productlist/donyaberry.jpg
    - assets/Productlist/icedcaramel.jpg
    - assets/Productlist/macha.jpg
    - assets/Productlist/matchaberry.jpg
    - assets/yawa.png
    - assets/branchopol.png
    - assets/branchdasmarinas.png
    - assets/branchbuhisan.png
    - assets/branchtabunok.png
    - assets/branchbooth.png
    - assets/branchlingayen.png
